# Generated by Django 2.1.3 on 2019-02-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footprint_user', models.ManyToManyField(blank=True, related_name='footprints_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='件名')),
                ('text', models.TextField(verbose_name='本文')),
                ('unread', models.BooleanField(default=False)),
                ('sending_date', models.DateTimeField(auto_now_add=True)),
                ('receiving_date', models.DateTimeField(auto_now_add=True)),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_route_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='公開しない')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('gender', models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, '男女問わない')], verbose_name='性別対象')),
                ('instrument', models.CharField(choices=[('ヴォーカル', 'ヴォーカル'), ('ギター', 'ギター'), ('ベース', 'ベース'), ('ドラム', 'ドラム'), ('キーボード', 'キーボード'), ('その他', 'その他')], max_length=10, verbose_name='募集楽器')),
                ('amateur_level', models.BooleanField(default=False, verbose_name='初心者歓迎')),
                ('age', models.IntegerField(choices=[(1, '10～20歳'), (2, '20～30歳'), (3, '30～40歳'), (4, '40～50歳'), (5, '50～60歳'), (6, '60～70歳')], verbose_name='年齢制限')),
                ('area', models.CharField(max_length=100, verbose_name='活動地域')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_comment', to='amateurband.Recruitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='件名')),
                ('text', models.TextField(verbose_name='本文')),
                ('sending_date', models.DateTimeField(auto_now_add=True)),
                ('receiving_date', models.DateTimeField(auto_now_add=True)),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='amateur_image/')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性')], null=True, verbose_name='性別')),
                ('age', models.IntegerField(blank=True, choices=[(1, '10～20歳'), (2, '20～30歳'), (3, '30～40歳'), (4, '40～50歳'), (5, '50～60歳'), (6, '60～70歳')], null=True, verbose_name='年齢')),
                ('instrument', models.CharField(blank=True, choices=[('ヴォーカル', 'ヴォーカル'), ('ギター', 'ギター'), ('ベース', 'ベース'), ('ドラム', 'ドラム'), ('キーボード', 'キーボード'), ('その他', 'その他')], max_length=10, null=True, verbose_name='パート楽器')),
                ('amateur_level', models.CharField(blank=True, choices=[('初心者', '初心者'), ('経験者', '経験者')], max_length=10, null=True, verbose_name='初心者？経験者？')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='活動地域')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
