# Generated by Django 2.1.3 on 2019-02-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateurband', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentcomment',
            name='admission',
            field=models.BooleanField(default=False),
        ),
    ]
