# Generated by Django 2.1.3 on 2018-12-19 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amateurband', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('instrument', models.CharField(blank=True, choices=[('ヴォーカル', 'ヴォーカル'), ('ギター', 'ギター'), ('ベース', 'ベース'), ('ドラム', 'ドラム'), ('キーボード', 'キーボード'), ('その他', 'その他')], max_length=10, null=True, verbose_name='募集楽器')),
                ('amateur_level', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, choices=[(1, '10～20'), (2, '20～30'), (3, '30～40'), (4, '40～50'), (5, '50～60'), (6, '60～70')], null=True, verbose_name='年齢')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
