# Generated by Django 2.1.3 on 2018-12-19 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amateurband', '0002_auto_20181220_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='ニックネーム')),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=2, verbose_name='性別')),
                ('instrument', models.CharField(choices=[('ヴォーカル', 'ヴォーカル'), ('ギター', 'ギター'), ('ベース', 'ベース'), ('ドラム', 'ドラム'), ('キーボード', 'キーボード'), ('その他', 'その他')], max_length=100, verbose_name='担当楽器')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, '10～20歳'), (2, '20～30歳'), (3, '30～40歳'), (4, '40～50歳'), (5, '50～60歳'), (6, '60～70歳')], null=True, verbose_name='年齢制限'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='amateur_level',
            field=models.BooleanField(default=False, verbose_name='初心者歓迎'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='記事を公開する'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
